/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.server;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ServiceResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ServiceResponse\",\"namespace\":\"com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.server\",\"fields\":[{\"name\":\"domain\",\"type\":{\"type\":\"record\",\"name\":\"Domain\",\"namespace\":\"com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.model\",\"fields\":[{\"name\":\"output\",\"type\":\"double\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.model.Domain domain;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ServiceResponse() {}

  /**
   * All-args constructor.
   */
  public ServiceResponse(com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.model.Domain domain) {
    this.domain = domain;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return domain;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: domain = (com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.model.Domain)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'domain' field.
   */
  public com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.model.Domain getDomain() {
    return domain;
  }

  /**
   * Sets the value of the 'domain' field.
   * @param value the value to set.
   */
  public void setDomain(com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.model.Domain value) {
    this.domain = value;
  }

  /** Creates a new ServiceResponse RecordBuilder */
  public static com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.server.ServiceResponse.Builder newBuilder() {
    return new com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.server.ServiceResponse.Builder();
  }
  
  /** Creates a new ServiceResponse RecordBuilder by copying an existing Builder */
  public static com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.server.ServiceResponse.Builder newBuilder(com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.server.ServiceResponse.Builder other) {
    return new com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.server.ServiceResponse.Builder(other);
  }
  
  /** Creates a new ServiceResponse RecordBuilder by copying an existing ServiceResponse instance */
  public static com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.server.ServiceResponse.Builder newBuilder(com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.server.ServiceResponse other) {
    return new com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.server.ServiceResponse.Builder(other);
  }
  
  /**
   * RecordBuilder for ServiceResponse instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ServiceResponse>
    implements org.apache.avro.data.RecordBuilder<ServiceResponse> {

    private com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.model.Domain domain;

    /** Creates a new Builder */
    private Builder() {
      super(com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.server.ServiceResponse.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.server.ServiceResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.domain)) {
        this.domain = data().deepCopy(fields()[0].schema(), other.domain);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ServiceResponse instance */
    private Builder(com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.server.ServiceResponse other) {
            super(com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.server.ServiceResponse.SCHEMA$);
      if (isValidValue(fields()[0], other.domain)) {
        this.domain = data().deepCopy(fields()[0].schema(), other.domain);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'domain' field */
    public com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.model.Domain getDomain() {
      return domain;
    }
    
    /** Sets the value of the 'domain' field */
    public com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.server.ServiceResponse.Builder setDomain(com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.model.Domain value) {
      validate(fields()[0], value);
      this.domain = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'domain' field has been set */
    public boolean hasDomain() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'domain' field */
    public com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.server.ServiceResponse.Builder clearDomain() {
      domain = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public ServiceResponse build() {
      try {
        ServiceResponse record = new ServiceResponse();
        record.domain = fieldSetFlags()[0] ? this.domain : (com.example.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.model.Domain) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
