/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.model;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Model {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Model\",\"namespace\":\"com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.model\",\"types\":[{\"type\":\"record\",\"name\":\"Domain\",\"fields\":[{\"name\":\"output\",\"type\":\"double\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends Model {
    public static final org.apache.avro.Protocol PROTOCOL = com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.model.Model.PROTOCOL;
  }
}