/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Methods {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Methods\",\"namespace\":\"com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server\",\"types\":[{\"type\":\"error\",\"name\":\"ServiceException\",\"namespace\":\"com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.rpc\",\"fields\":[{\"name\":\"message\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]},{\"type\":\"record\",\"name\":\"Domain\",\"namespace\":\"com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.model\",\"fields\":[{\"name\":\"output\",\"type\":\"double\"}]},{\"type\":\"record\",\"name\":\"ServiceRequest\",\"fields\":[{\"name\":\"input\",\"type\":{\"type\":\"array\",\"items\":\"double\"}}]},{\"type\":\"record\",\"name\":\"ServiceResponse\",\"fields\":[{\"name\":\"domain\",\"type\":\"com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.model.Domain\"}]},{\"type\":\"record\",\"name\":\"MetadataRequest\",\"fields\":[{\"name\":\"pretty\",\"type\":\"boolean\",\"default\":false}]},{\"type\":\"record\",\"name\":\"MetadataResponse\",\"fields\":[{\"name\":\"notebook\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}],\"messages\":{\"predict\":{\"request\":[{\"name\":\"request\",\"type\":\"ServiceRequest\"}],\"response\":\"ServiceResponse\",\"errors\":[\"com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException\"]},\"notebook\":{\"request\":[{\"name\":\"request\",\"type\":\"MetadataRequest\"}],\"response\":\"MetadataResponse\",\"errors\":[\"com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException\"]}}}");
  com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceResponse predict(com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceRequest request) throws org.apache.avro.AvroRemoteException, com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException;
  com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.MetadataResponse notebook(com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.MetadataRequest request) throws org.apache.avro.AvroRemoteException, com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException;

  @SuppressWarnings("all")
  public interface Callback extends Methods {
    public static final org.apache.avro.Protocol PROTOCOL = com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.Methods.PROTOCOL;
    void predict(com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceRequest request, org.apache.avro.ipc.Callback<com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceResponse> callback) throws java.io.IOException;
    void notebook(com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.MetadataRequest request, org.apache.avro.ipc.Callback<com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.MetadataResponse> callback) throws java.io.IOException;
  }
}