/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ServiceRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ServiceRequest\",\"namespace\":\"com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server\",\"fields\":[{\"name\":\"input\",\"type\":{\"type\":\"array\",\"items\":\"double\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<java.lang.Double> input;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ServiceRequest() {}

  /**
   * All-args constructor.
   */
  public ServiceRequest(java.util.List<java.lang.Double> input) {
    this.input = input;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return input;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: input = (java.util.List<java.lang.Double>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'input' field.
   */
  public java.util.List<java.lang.Double> getInput() {
    return input;
  }

  /**
   * Sets the value of the 'input' field.
   * @param value the value to set.
   */
  public void setInput(java.util.List<java.lang.Double> value) {
    this.input = value;
  }

  /** Creates a new ServiceRequest RecordBuilder */
  public static com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceRequest.Builder newBuilder() {
    return new com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceRequest.Builder();
  }
  
  /** Creates a new ServiceRequest RecordBuilder by copying an existing Builder */
  public static com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceRequest.Builder newBuilder(com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceRequest.Builder other) {
    return new com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceRequest.Builder(other);
  }
  
  /** Creates a new ServiceRequest RecordBuilder by copying an existing ServiceRequest instance */
  public static com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceRequest.Builder newBuilder(com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceRequest other) {
    return new com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceRequest.Builder(other);
  }
  
  /**
   * RecordBuilder for ServiceRequest instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ServiceRequest>
    implements org.apache.avro.data.RecordBuilder<ServiceRequest> {

    private java.util.List<java.lang.Double> input;

    /** Creates a new Builder */
    private Builder() {
      super(com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceRequest.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.input)) {
        this.input = data().deepCopy(fields()[0].schema(), other.input);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ServiceRequest instance */
    private Builder(com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceRequest other) {
            super(com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceRequest.SCHEMA$);
      if (isValidValue(fields()[0], other.input)) {
        this.input = data().deepCopy(fields()[0].schema(), other.input);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'input' field */
    public java.util.List<java.lang.Double> getInput() {
      return input;
    }
    
    /** Sets the value of the 'input' field */
    public com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceRequest.Builder setInput(java.util.List<java.lang.Double> value) {
      validate(fields()[0], value);
      this.input = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'input' field has been set */
    public boolean hasInput() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'input' field */
    public com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.server.ServiceRequest.Builder clearInput() {
      input = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public ServiceRequest build() {
      try {
        ServiceRequest record = new ServiceRequest();
        record.input = fieldSetFlags()[0] ? this.input : (java.util.List<java.lang.Double>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
