/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ServiceException extends org.apache.avro.specific.SpecificExceptionBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"error\",\"name\":\"ServiceException\",\"namespace\":\"io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc\",\"fields\":[{\"name\":\"message\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String message$;

  public ServiceException() {
    super();
  }
  
  public ServiceException(Object value) {
    super(value);
  }

  public ServiceException(Throwable cause) {
    super(cause);
  }

  public ServiceException(Object value, Throwable cause) {
    super(value, cause);
  }
  
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return message$;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: message$ = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'message$' field.
   */
  public java.lang.String getMessage$() {
    return message$;
  }

  /**
   * Sets the value of the 'message$' field.
   * @param value the value to set.
   */
  public void setMessage$(java.lang.String value) {
    this.message$ = value;
  }

  /** Creates a new ServiceException RecordBuilder */
  public static io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException.Builder newBuilder() {
    return new io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException.Builder();
  }
  
  /** Creates a new ServiceException RecordBuilder by copying an existing Builder */
  public static io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException.Builder newBuilder(io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException.Builder other) {
    return new io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException.Builder(other);
  }
  
  /** Creates a new ServiceException RecordBuilder by copying an existing ServiceException instance */
  public static io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException.Builder newBuilder(io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException other) {
    return new io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException.Builder(other);
  }
  
  /**
   * RecordBuilder for ServiceException instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificErrorBuilderBase<ServiceException>
    implements org.apache.avro.data.ErrorBuilder<ServiceException> {

    private java.lang.String message$;

    /** Creates a new Builder */
    private Builder() {
      super(io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.message$)) {
        this.message$ = data().deepCopy(fields()[0].schema(), other.message$);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ServiceException instance */
    private Builder(io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException other) {
      super(other);
      if (isValidValue(fields()[0], other.message$)) {
        this.message$ = data().deepCopy(fields()[0].schema(), other.message$);
        fieldSetFlags()[0] = true;
      }
    }

    @Override
    public io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException.Builder setValue(Object value) {
      super.setValue(value);
      return this;
    }
    
    @Override
    public io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException.Builder clearValue() {
      super.clearValue();
      return this;
    }

    @Override
    public io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException.Builder setCause(Throwable cause) {
      super.setCause(cause);
      return this;
    }
    
    @Override
    public io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException.Builder clearCause() {
      super.clearCause();
      return this;
    }

    /** Gets the value of the 'message$' field */
    public java.lang.String getMessage$() {
      return message$;
    }
    
    /** Sets the value of the 'message$' field */
    public io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException.Builder setMessage$(java.lang.String value) {
      validate(fields()[0], value);
      this.message$ = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'message$' field has been set */
    public boolean hasMessage$() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'message$' field */
    public io.kensu.decisiontreefied_com.datafellas.g3nerator.modeloutput_0.rpc.ServiceException.Builder clearMessage$() {
      message$ = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public ServiceException build() {
      try {
        ServiceException record = new ServiceException(getValue(), getCause());
        record.message$ = fieldSetFlags()[0] ? this.message$ : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
