/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.rpc;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface RPC {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"RPC\",\"namespace\":\"com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.rpc\",\"types\":[{\"type\":\"error\",\"name\":\"ServiceException\",\"fields\":[{\"name\":\"message\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends RPC {
    public static final org.apache.avro.Protocol PROTOCOL = com.example.pipeline_decision_trees_simple_model_final.snb_com.datafellas.g3nerator.modeloutput_0.rpc.RPC.PROTOCOL;
  }
}